### ISSUE TITLE
small error in document count 

### ISSUE THREAD

**Issue by suryabulusu** [srush/jax-lda#3]
I think the code should be `DOCUMENTS = i + 1` in [line 33](https://github.com/srush/jax-lda/blob/aa5da6cf198d3767dd60edf3644dfe0f7184df00/lda.py#L33)

The maximum value in `docs` array is `DOCUMENTS`, the last document. Currently, `topic_document` is not accounting for topics in the last document since its shape is `(DOCUMENTS, TOPICS)`.

We can verify by checking `assert np.sum(topic_word) == np.sum(topic_document)` -- which fails currently.

**Comment by srush** [comment]
Thanks. Btw, this code is really just a test implementation. It is likely very slow, so use with caution.
